### ISSUE TITLE
FlexBasisMaxContent, FlexBasisFitContent, FlexBasisStretch missing from YGNode

### ISSUE THREAD

**Issue by antokhio** [Haselnussbomber/YogaSharp#1]
https://github.com/Haselnussbomber/YogaSharp/blob/f35419823bf8a9b8106585a103a0793b49a339bb/YogaSharp/Interop.YGNodeStyle.cs#L98

hi was syncing my fork noticed few styles are missing, looks like a typo...

**Comment by Haselnussbomber** [comment]
They exist: https://github.com/facebook/yoga/blob/main/yoga/YGNodeStyle.h#L67-L69
I just forgot to add them to YGNode, too. Again.

**Comment by Haselnussbomber** [comment]
Thanks for telling me. Added with 5491645cc9d11be69c79cd50b93713d3a4609501. 🙂
